### ISSUE TITLE
It seems impossible to drag the last view in a GoldenLayout stack somewhere else

### ISSUE THREAD

**Issue by mfranke93** [UniStuttgart-VISUS/damast#233]
Probably caused by the recent GoldenLayout version upgrade.

**Comment by mfranke93** [comment]
Ultimately, this seems to be caused by the components themselves not being closable. Removing the `isClosable: false` from the configuration, and using the new `root` property instead of the `components` property in the config, solves this issue. However, views are now closable.

The solution is simple, but a bit ugly. However, I see no good alternative. I had no success intercepting the close events reliably, so my proposed solution is to hide the close buttons and make them not clickable:

``` css
.lm_header .lm_close_tab {
  visibility: hidden;
  pointer-events: none;
}
```
